export const onePieceTheories = {
  en: [
    "The One Piece is a World-Changing Secret 🌍📜 - Forget gold—it's a treasure that will turn the world upside down, uniting nations and destroying the World Government's lies.",
    "Joy Boy Was a Revolutionary King 👑🔥 - He wasn't just a dreamer; Joy Boy led the Ancient Kingdom against tyranny, leaving behind weapons to finish the fight.",
    "The Straw Hat is a Royal Crown 🎩👑 - The hat is more than a symbol—it was once worn by the king of the Ancient Kingdom.",
    "Raftel (Laughtale) Holds the Ancient Kingdom's Legacy 🗺️🏴‍☠️ - The true history of the world is carved into the land itself, waiting for someone to claim it.",
    "The Will of D is a War Cry ⚔️🌀 - Those with the initial 'D' are destined to lead the rebellion against oppression and fulfill Joy Boy's promise.",
    "Blackbeard is a Three-Headed Monster 👹🍎🍎 - His unique body harbors three souls, explaining his ability to wield multiple Devil Fruits.",
    "The Red Line Will Shatter to Create the All Blue 🌊🐟 - By destroying the Red Line, Luffy will unite all the seas, fulfilling Sanji's lifelong dream.",
    "The Ancient Kingdom Was the Pirate Dreamland 🏴‍☠️✨ - A land where freedom reigned, the Ancient Kingdom was the origin of the pirate code.",
    "Shanks is Secretly Protecting the One Piece 🤐🎩 - Far from being a carefree pirate, Shanks is guarding the treasure to ensure it falls into the right hands.",
    "Uranus is a Weather-Control Machine ☁️⚡ - One of the Ancient Weapons, Uranus can manipulate storms and winds, explaining the Grand Line's chaotic weather.",
    "Devil Fruits Were Created to Rebel Against Nature 🍎🌊 - The Ancient Kingdom designed Devil Fruits to defy natural laws and empower humanity.",
    "Imu is the Void Century's Sole Survivor 🕰️👑 - The ruler of the World Government is the last remaining enemy of the Ancient Kingdom, ruling in secrecy for centuries.",
    "The Moon Holds the Truth About the Ancient Kingdom 🌕🚀 - The people of the Ancient Kingdom may have fled to the moon to escape annihilation, leaving clues behind.",
    "Vegapunk Will Unlock the Power of the Sea 🧠🌊 - The genius scientist knows how Devil Fruits are made—and their connection to the oceans.",
    "Zoro's Ancestors Were Wano's Greatest Swordsmiths ⚔️⛩️ - The legendary Shimotsuki family didn't just create swords; they shaped the samurai legacy of Wano.",
    "The One Piece is the Rio Poneglyph 🔓📜 - All roads lead to a single artifact that will reveal the untold story of the Void Century.",
    "Koby Will Join the Straw Hats as a True Pirate 🛡️🏴‍☠️ - Once a Marine, Koby will embrace his true calling as part of Luffy's crew.",
    "The Straw Hats Are Reincarnations of Ancient Heroes 🌞🌀 - Each crew member reflects a hero from the Ancient Kingdom, destined to finish the fight.",
    "Sanji's Flames Come from His Lunarian DNA 🔥👼 - Judge's experiments weren't just enhancements—they awakened Sanji's connection to King's fire-wielding race.",
  ],
  jp: [
    "「ワンピース」は世界を変える秘密 🌍📜 - 金銀財宝ではなく、世界をひっくり返し、国々を結びつけ、世界政府の嘘を暴く宝である。",
    "ジョイボーイは革命の王 👑🔥 - ただの夢想家ではない。古代王国を率いて圧政に立ち向かい、戦いを終わらせるための兵器を遺した。",
    "麦わら帽子は王冠だった 🎩👑 - ただの象徴ではなく、かつて古代王国の王が身につけていた王冠だった。",
    "ラフテル（ロードスター島）は古代王国の遺産を抱く地 🗺️🏴‍☠️ - 世界の真の歴史が大地に刻まれ、受け継ぐ者を待っている。",
    "「D」の意志は戦いの号令 ⚔️🌀 - 「D」の名を持つ者は、圧政に抗う反乱の先導者となり、ジョイボーイの誓いを果たす運命にある。",
    '黒ひげは"三つの頭を持つ怪物" 👹🍎🍎 - 彼の特殊な肉体には三つの魂が宿っており、複数の悪魔の実を持てる理由となっている。',
    "赤い土の大陸は砕かれ、「オールブルー」が生まれる 🌊🐟 - ルフィが赤い土の大陸を破壊することで、全ての海が一つに繋がり、サンジの夢が叶う。",
    "古代王国は「海賊の楽園」だった 🏴‍☠️✨ - 自由を重んじる国であり、海賊の理念の源となった場所。",
    "シャンクスは「ワンピース」を密かに守っている 🤐🎩 - 気ままな海賊に見えて、実は宝を正しい者の手に渡るまで守っている。",
    "ウラヌスは天候を操る兵器 ☁️⚡ - 古代兵器の一つであり、嵐や風を操る力を持ち、偉大なる航路の異常気象の原因となっている。",
    "悪魔の実は「自然への反逆」として生み出された 🍎🌊 - 古代王国が自然の法則を覆し、人類を強化するために作った。",
    "イムは「空白の100年」の唯一の生き残り 🕰️👑 - 世界政府を統べる存在であり、古代王国を滅ぼした後、長きにわたり影から世界を支配している。",
    "月には「古代王国の真実」が隠されている 🌕🚀 - 古代王国の民は滅亡を逃れるため月へ旅立ち、その痕跡を残した可能性がある。",
    "ベガパンクは「海の力」を解き明かす 🧠🌊 - 天才科学者である彼は、悪魔の実の仕組みとそれが海とどう関係しているのかを知っている。",
    "ゾロの祖先は「ワノ国最強の刀鍛冶」 ⚔️⛩️ - 伝説の霜月家は、単なる刀鍛冶ではなく、ワノ国の侍の歴史そのものを築いた一族である。",
    "「ワンピース」の正体は「リオ・ポーネグリフ」 🔓📜 - 全ての道は、一つの遺物に繋がり、「空白の100年」の真実を明らかにする。",
    "コビーは「真の海賊」として麦わらの一味に加わる 🛡️🏴‍☠️ - かつて海軍だった彼は、ついに自分の本当の使命を受け入れ、ルフィの仲間となる。",
    "麦わらの一味は「古代の英雄たちの生まれ変わり」 🌞🌀 - それぞれが古代王国の英雄の魂を受け継ぎ、未完の戦いを終わらせる運命を持つ。",
    "サンジの炎は「ルナーリア族の血」によるもの 🔥👼 - ジャッジの改造は単なる強化ではなく、彼の中に眠るキングと同じ「炎を操る種族」の力を呼び覚ました。",
  ],
};
