export const onePieceTheories = {
  en: [
    "the One Piece is a world-changing secret 🌍📜 - forget gold—it's a treasure that will turn the world upside down, uniting nations and destroying the World Government's lies.",
    "Joy Boy was a revolutionary king 👑🔥 - he wasn't just a dreamer; Joy Boy led the Ancient Kingdom against tyranny, leaving behind weapons to finish the fight.",
    "the straw hat is a royal crown 🎩👑 - the hat is more than a symbol—it was once worn by the king of the Ancient Kingdom.",
    "Raftel (Laughtale) holds the Ancient Kingdom's legacy 🗺️🏴‍☠️ - the true history of the world is carved into the land itself, waiting for someone to claim it.",
    "the Will of D is a war cry ⚔️🌀 - those with the initial 'D' are destined to lead the rebellion against oppression and fulfill Joy Boy's promise.",
    "Blackbeard is a three-headed monster 👹🍎🍎 - his unique body harbors three souls, explaining his ability to wield multiple Devil Fruits.",
    "the Red Line will shatter to create the All Blue 🌊🐟 - by destroying the Red Line, Luffy will unite all the seas, fulfilling Sanji's lifelong dream.",
    "the Ancient Kingdom was the pirate dreamland 🏴‍☠️✨ - a land where freedom reigned, the Ancient Kingdom was the origin of the pirate code.",
    "Shanks is secretly protecting the One Piece 🤐🎩 - far from being a carefree pirate, Shanks is guarding the treasure to ensure it falls into the right hands.",
    "Uranus is a weather-control machine ☁️⚡ - one of the Ancient Weapons, Uranus can manipulate storms and winds, explaining the Grand Line's chaotic weather.",
    "Devil Fruits were created to rebel against nature 🍎🌊 - the Ancient Kingdom designed Devil Fruits to defy natural laws and empower humanity.",
    "Imu is the Void Century's sole survivor 🕰️👑 - the ruler of the World Government is the last remaining enemy of the Ancient Kingdom, ruling in secrecy for centuries.",
    "the moon holds the truth about the Ancient Kingdom 🌕🚀 - the people of the Ancient Kingdom may have fled to the moon to escape annihilation, leaving clues behind.",
    "Vegapunk will unlock the power of the sea 🧠🌊 - the genius scientist knows how Devil Fruits are made—and their connection to the oceans.",
    "Zoro's ancestors were Wano's greatest swordsmiths ⚔️⛩️ - the legendary Shimotsuki family didn't just create swords; they shaped the samurai legacy of Wano.",
    "the One Piece is the Rio Poneglyph 🔓📜 - all roads lead to a single artifact that will reveal the untold story of the Void Century.",
    "Koby will join the Straw Hats as a true pirate 🛡️🏴‍☠️ - once a Marine, Koby will embrace his true calling as part of Luffy's crew.",
    "the Straw Hats are reincarnations of ancient heroes 🌞🌀 - each crew member reflects a hero from the Ancient Kingdom, destined to finish the fight.",
    "Sanji's flames come from his Lunarian DNA 🔥👼 - Judge's experiments weren't just enhancements—they awakened Sanji's connection to King's fire-wielding race.",
    "Luffy IS the Sun God Nika ☀️🥁 - Gear 5 isn't just a power-up—Luffy's fruit was always the Hito Hito no Mi, Model: Nika. the World Government renamed it to hide the truth for 800 years.",
    "Crocodile's secret: Ivankov knows everything 🐊👄 - Ivankov has leverage over Crocodile because he changed Crocodile's body in the past. that's the secret that keeps Sir Croc in line.",
    "the One Piece is a party that never ended 🍻🎶 - Roger laughed because the 'treasure' is Bink's Sake—a promise to throw the biggest feast the world has ever seen, uniting every race and nation.",
    "Rocks D. Xebec lives on through Blackbeard 💀🏴‍☠️ - Xebec's will—or his literal soul—passed to Blackbeard at God Valley. that's why Teach inherited his ambition to rule everything.",
    "Luffy will destroy Fishman Island to save it 🐟💥 - Madam Shyarly's prophecy is real, but Luffy destroys the island to free the fishmen and bring them to the surface world where they belong.",
    "Buggy will accidentally become Pirate King 🤡👑 - the ultimate gag character keeps failing upward. his luck is the real Ancient Weapon—and Oda has been setting up the biggest punchline in manga history.",
    "the giant straw hat in Mariejois belongs to Nika 👒❄️ - Imu keeps it frozen as a trophy from the Void Century war. it's proof the World Government defeated the Sun God once—and fears his return.",
    "Dragon's power is the storm itself 🌪️⛈️ - Monkey D. Dragon ate a Mythical Zoan fruit that lets him become a storm dragon or wind deity, explaining every convenient gust of wind in the series.",
  ],
  jp: [
    "「ワンピース」は世界を変える秘密 🌍📜 - 金銀財宝ではなく、世界をひっくり返し、国々を結びつけ、世界政府の嘘を暴く宝である。",
    "ジョイボーイは革命の王 👑🔥 - ただの夢想家ではない。古代王国を率いて圧政に立ち向かい、戦いを終わらせるための兵器を遺した。",
    "麦わら帽子は王冠だった 🎩👑 - ただの象徴ではなく、かつて古代王国の王が身につけていた王冠だった。",
    "ラフテル（ロードスター島）は古代王国の遺産を抱く地 🗺️🏴‍☠️ - 世界の真の歴史が大地に刻まれ、受け継ぐ者を待っている。",
    "「D」の意志は戦いの号令 ⚔️🌀 - 「D」の名を持つ者は、圧政に抗う反乱の先導者となり、ジョイボーイの誓いを果たす運命にある。",
    '黒ひげは"三つの頭を持つ怪物" 👹🍎🍎 - 彼の特殊な肉体には三つの魂が宿っており、複数の悪魔の実を持てる理由となっている。',
    "赤い土の大陸は砕かれ、「オールブルー」が生まれる 🌊🐟 - ルフィが赤い土の大陸を破壊することで、全ての海が一つに繋がり、サンジの夢が叶う。",
    "古代王国は「海賊の楽園」だった 🏴‍☠️✨ - 自由を重んじる国であり、海賊の理念の源となった場所。",
    "シャンクスは「ワンピース」を密かに守っている 🤐🎩 - 気ままな海賊に見えて、実は宝を正しい者の手に渡るまで守っている。",
    "ウラヌスは天候を操る兵器 ☁️⚡ - 古代兵器の一つであり、嵐や風を操る力を持ち、偉大なる航路の異常気象の原因となっている。",
    "悪魔の実は「自然への反逆」として生み出された 🍎🌊 - 古代王国が自然の法則を覆し、人類を強化するために作った。",
    "イムは「空白の100年」の唯一の生き残り 🕰️👑 - 世界政府を統べる存在であり、古代王国を滅ぼした後、長きにわたり影から世界を支配している。",
    "月には「古代王国の真実」が隠されている 🌕🚀 - 古代王国の民は滅亡を逃れるため月へ旅立ち、その痕跡を残した可能性がある。",
    "ベガパンクは「海の力」を解き明かす 🧠🌊 - 天才科学者である彼は、悪魔の実の仕組みとそれが海とどう関係しているのかを知っている。",
    "ゾロの祖先は「ワノ国最強の刀鍛冶」 ⚔️⛩️ - 伝説の霜月家は、単なる刀鍛冶ではなく、ワノ国の侍の歴史そのものを築いた一族である。",
    "「ワンピース」の正体は「リオ・ポーネグリフ」 🔓📜 - 全ての道は、一つの遺物に繋がり、「空白の100年」の真実を明らかにする。",
    "コビーは「真の海賊」として麦わらの一味に加わる 🛡️🏴‍☠️ - かつて海軍だった彼は、ついに自分の本当の使命を受け入れ、ルフィの仲間となる。",
    "麦わらの一味は「古代の英雄たちの生まれ変わり」 🌞🌀 - それぞれが古代王国の英雄の魂を受け継ぎ、未完の戦いを終わらせる運命を持つ。",
    "サンジの炎は「ルナーリア族の血」によるもの 🔥👼 - ジャッジの改造は単なる強化ではなく、彼の中に眠るキングと同じ「炎を操る種族」の力を呼び覚ました。",
    "ルフィこそが太陽の神ニカ ☀️🥁 - ギア5は単なるパワーアップではない。ルフィの実は最初から「ヒトヒトの実 モデル：ニカ」だった。世界政府は800年間その真実を隠してきた。",
    "クロコダイルの秘密：イワンコフは全てを知っている 🐊👄 - イワンコフがクロコダイルに対して切り札を持つのは、過去に彼の体を変えたから。それが「サー・クロコ」を従わせる秘密。",
    "「ワンピース」は終わらない宴 🍻🎶 - ロジャーが笑ったのは、「宝」の正体がビンクスの酒——全種族・全国家が集う、世界最大の宴を開くという約束だったから。",
    "ロックス・D・ジーベックは黒ひげの中に生きている 💀🏴‍☠️ - ジーベックの意志、あるいは魂そのものが、ゴッドバレーでティーチに受け継がれた。全てを支配するという野望の源泉はそこにある。",
    "ルフィは魚人島を壊して救う 🐟💥 - マダム・シャーリーの予言は本物。だがルフィが島を壊すのは、魚人たちを解放し、地上の世界へ導くためである。",
    "バギーはうっかり海賊王になる 🤡👑 - 究極のギャグキャラは失敗するたびにのし上がる。彼の「運」こそが真の古代兵器——尾田先生は漫画史上最大のオチを仕込んでいる。",
    "マリージョアの巨大な麦わら帽子はニカのもの 👒❄️ - イムはそれを空白の100年の戦利品として凍結保存している。世界政府がかつて太陽の神を倒した証拠——そしてその復活を恐れている。",
    "ドラゴンの能力は「嵐そのもの」 🌪️⛈️ - モンキー・D・ドラゴンは嵐龍か風神の幻獣種を食べた。物語中のあらゆる「都合のいい突風」の説明がつく。",
  ],
};

export const onePieceBounties = [
  '3,000,000,000',
  '4,048,900,000',
  '4,388,000,000',
  '1,500,000,000',
  '5,564,800,000',
  '500,000,000',
  '3,189,000,000',
];

export const onePieceEmojis = [
  "⚔️",
  "🏴‍☠️",
  "🗺️",
  "⛵",
  "🌊",
  "🍖",
  "👒",
  "🗡️",
  "🍊",
  "⚓",
  "🐚",
  "🐙",
  "🐋",
  "💰",
  "💎",
  "🦈",
  "👐",
  "🧜‍♀️",
  "🦾",
  "☠︎",
  "🤜",
  "🐲",
  "🌎",
];
